[model.mesh]
density = 110
debug_view = false
order = 1

[model.geometry]
outer_profile_mode = "circular"
anterior_projection_scale = 1.0
superior_pole_scale = 1.0

[material.tumor]
tumorous = false

[material.glandular.hetero]
enabled = false
auto_generate = false
