[model.mesh]
density = 140
debug_view = false

[material.tumor]
tumorous = false

[material.glandular.hetero]
enabled = true
auto_generate = false

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05992, -0.00335,]
width = 0.003700
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05183, -0.00670,]
width = 0.003400
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.04375, -0.01005,]
width = 0.003100
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05949, -0.00204,]
width = 0.003700
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05098, -0.00409,]
width = 0.003400
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.04248, -0.00613,]
width = 0.003100
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05928, -0.00069,]
width = 0.003700
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05055, -0.00137,]
width = 0.003400
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.04183, -0.00206,]
width = 0.003100
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05928, 0.00069,]
width = 0.003700
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05055, 0.00137,]
width = 0.003400
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.04183, 0.00206,]
width = 0.003100
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05949, 0.00204,]
width = 0.003700
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05098, 0.00409,]
width = 0.003400
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.04248, 0.00613,]
width = 0.003100
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05992, 0.00335,]
width = 0.003700
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.05183, 0.00670,]
width = 0.003400
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[[material.glandular.hetero.lobules]]
center = [ 0.00000, 0.04375, 0.01005,]
width = 0.003100
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0



