[model.mesh]
density = 145
debug_view = false

[material.tumor]
tumorous = false

[material.adipose.hetero]
enabled = true
radial_center = [ 0.0, 0.0, 0.0,]
radial_L = 0.05
radial_alpha_c1 = 35.0
radial_alpha_c2 = 25.0
radial_alpha_rho = 40.0
auto_generate = false
n_lobes = 6
n_per_lobe = 5
nipple = [ 0.0, 0.035, 0.0,]
lobe_length = 0.03
spread_angle = 2.0
width = 0.004
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0
