[model.mesh]
density = 90
debug_view = false
order = 2

[model.geometry]
outer_profile_mode = "elliptic"
anterior_projection_scale = 1.08
superior_pole_scale = 0.98

[material.tumor]
tumorous = false

[material.glandular.hetero]
enabled = false
auto_generate = false
