[model.mesh]
density = 165
debug_view = false

[model.geometry.asymmetry]
enabled = true
scale_y = 1.08
scale_z = 0.92

[material.tumor]
tumorous = false

[material.glandular.hetero]
enabled = true
auto_generate = true
n_lobes = 6
n_per_lobe = 5
lobe_length = 0.03
spread_angle = 2.0
width = 0.0042
amp_c1 = 70.0
amp_c2 = 55.0
amp_rho = 35.0

[simulation.output]
extra_vars = [ "relative volume", "Lagrange strain", "J", "c1", "c2", "density",]
